name: win11 desktop tools

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore Exelus.Win11DesktopSwitchAnimatior/Exelus.Win11DesktopSwitchAnimatior.sln
    - name: Build
      run: dotnet build Exelus.Win11DesktopSwitchAnimatior/Exelus.Win11DesktopSwitchAnimatior/Exelus.Win11DesktopSwitchAnimatior.csproj --configuration Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: desktop_tools
        # Destination path
        path: D:\a\Win11DesktopSwitchAnimation\Win11DesktopSwitchAnimation\Exelus.Win11DesktopSwitchAnimatior\Exelus.Win11DesktopSwitchAnimatior\bin\Release
